name: playwright
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl-and-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: npm install
        run: npm i
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: cpanm -n --installdeps .
      - name: Run tests
        run: prove -l t/*.t
